### PR TITLE
Updated breakage after futures 0.2.0 publish

### PR DESCRIPTION
**Pull request by przygienda**
well, fixing loose Cargo.toml ...

### CODE REVIEW

**Comment by Keruspe** [comment]
@stepancheg this really is a blocker right now. tokio-tls-api cannot be used without this change

**Comment by stepancheg** [comment]
I’m on vacation now without my laptop, returning tomorrow, going to merge and publish tomorrow. Sorry for inconvenience!

**Comment by stepancheg** [comment]
Published 0.1.19.

**Comment by stepancheg** [comment]
Thanks!

**Pull request closed without merging**
