### PR TITLE
tls-api: update native-tls to 0.2

### PR DESCRIPTION
**Pull request by awakecoding**
This PR updates native-tls to 0.2, fixing issue https://github.com/stepancheg/rust-tls-api/issues/26

Unit tests pass after the API upgrade

### CODE REVIEW

**Comment by awakecoding** [comment]
@stepancheg any update on this?

**Comment by stepancheg** [comment]
Going to do it this week. Sorry for delay!

**Comment by stepancheg** [comment]
Published version 0.2.0.

**Comment by stepancheg** [comment]
Thanks!

**Comment by awakecoding** [comment]
@stepancheg thanks to you :)

**Pull request merged**
